### ISSUE TITLE
使用html模板导出PDF时，多页表格数据展示叠加错乱

### ISSUE THREAD

**Issue by lht-study** [dotnetcore/Magicodes.IE#146]
使用html模板导出PDF时，如果表格数据多页的话，会把第一页的部分内容放到第二页的表头那里，导致显示叠加
![image](https://user-images.githubusercontent.com/48585198/92092834-29b20080-ee05-11ea-99e2-7abc5d8c061e.png)

**Comment by lht-study** [comment]
已解决

**Comment by zhanghaiboshiwo** [comment]
怎么解决的大佬

**Comment by chen1tian** [comment]
遇到过同样问题，在css中增加：
```css
table, tr, td, th, tbody, thead, tfoot {
    page-break-inside: avoid !important;
}
```
就能解决。
